# 0. 环境安装与配置(练习1.5)
## 0.1 Python环境配置
+ https://docs.anaconda.com/anaconda/install/windows/
+ https://docs.anaconda.com/free/anaconda/install/mac-os/
+ https://docs.anaconda.com/anaconda/install/linux/

https://anaconda.org/conda-forge/keras
https://scikit-learn.org/stable/install.html

## 0.2 R环境配置
+ https://www.rstudio.com/
+ https://cran.r-project.org/web/packages/caret/vignettes/caret.html
+ https://keras.rstudio.com/reference/install_keras.html

# 1. Numpy基础

In [52]:
# 引入numpy包
import numpy as np

# 定义一维数组
a = np.arange(6)
print(a,'a')
# 定义二维数组
b = np.arange(12).reshape(4,3)
print(b,'b')
# 定义三维数组
c = np.arange(24).reshape(2,3,4)
print(c,'c')

[0 1 2 3 4 5] a
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] b
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] c


In [53]:
# 特殊矩阵
# 全0矩阵
a = np.zeros((2,2))
# 全1矩阵
b = np.ones((1,2))
# 常数矩阵
c = np.full((2,2),7)
print(c)
# 单位矩阵
d = np.eye(4)
print(d)
# 随机矩阵
e = np.random.random((2,2))
print(e)

[[7 7]
 [7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.99577289 0.56480434]
 [0.41112328 0.98298324]]


In [54]:
# 初始化3*4的矩阵
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
# 矩阵索引
b = a[:2, 1:3]
print(b)
# 矩阵索引
print(a[0, 1]) # Prints "2"
b[0, 0] = 77 # 矩阵赋值
print(a[0, 1]) # Prints "77"

# 深度拷贝
c = a.copy()
c[0,1] = -1
print(a[0,1])
print(c[0,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77
77
-1


In [55]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)
row_r1 = a[1, :]
print("a的第1行")
print(a.shape)
print("================")
print(a[3,:])
row_r2 = a[1:2, :]
print("a的第1到3行")
print(a[1:3,:])

print(row_r1.shape)
print(row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]

print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
a的第1行
(3, 4)


IndexError: index 3 is out of bounds for axis 0 with size 3

## 1.1 矩阵的数学运算

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
print(x)
print(y)
# Elementwise sum; both produce the array
# [[ 6.0 8.0]
# [10.0 12.0]]
print(x + y)
print(np.add(x, y))
# Elementwise difference; both produce the array
# [[-4.0 -4.0]
# [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))
# Elementwise product; both produce the array
# [[ 5.0 12.0]
# [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))
# Elementwise division; both produce the array
# [[ 0.2 0.33333333]
# [ 0.42857143 0.5 ]]
print(x / y)
print(np.divide(x, y))
# Elementwise square root; produces the array
# [[ 1. 1.41421356]
# [ 1.73205081 2. ]]
print(np.sqrt(x))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
x = np.array([[1,2],[3,4]])
print(np.mean(x)) # Compute sum of all elements; prints "10"
print(np.mean(x, axis=0)) # Compute sum of each column; prints "[4 6]"
print(np.mean(x, axis=1)) # Compute sum of each row; prints "[3 7]"
print(' ----------')
x = np.array([[1,2], [3,4]])
print(x) # Prints "[[1 2]
# [3 4]]"
print(x.T) # Prints "[[1 3]
# [2 4]]"
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v) # Prints "[1 2 3]"
print(v.T) # Prints "[1 2 3]"
print(' ----------')
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Create an empty matrix with the same shape as x
# 0初始化
y = np.zeros(x.shape)
y = np.ones(x.shape)
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] * v

# Now y is the following
# [[ 2 2 4]
# [ 5 5 7]
# [ 8 8 10]
# [11 11 13]]
print(y)

10
[4 6]
[3 7]
 ----------
[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]
 ----------
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [58]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
print("a========")
print(a)
print("b========")
print(b)

vertical_stack = np.vstack((a,b))
print("vertical result")
print(vertical_stack)

horizontal_stack = np.hstack((a,b))
print("Hori result")
print(horizontal_stack)


a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
ab = np.concatenate((a, b), axis=0)
print(ab, '  concatenate  axis=0')

ab = np.concatenate((a, b.T), axis=1)  # note b.T is same is b.transpose()
print(ab, '  concatenate  axis=1')

ab = np.concatenate((a, b), axis=None)
print(ab, '  concatenate  axis= none')

a========
[1 2 3]
b========
[2 3 4]
vertical result
[[1 2 3]
 [2 3 4]]
Hori result
[1 2 3 2 3 4]
[[1 2]
 [3 4]
 [5 6]]   concatenate  axis=0
[[1 2 5]
 [3 4 6]]   concatenate  axis=1
[1 2 3 4 5 6]   concatenate  axis= none
